development:
  adapter: postgresql
  encoding: unicode
  database: rails-expense-report-postgres_development
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: rails-expense-report-postgres_test
  pool: 5
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: rails-expense-report-postgres_production
  pool: 5
  username: postgres
  password: postgres
